spring:
  application:
    name: AggregatorService

server:
  port: 8084

services:
  showService:
    baseUrl: ${SHOW_SERVICE_BASE_URL:http://localhost:8081}
    timeOut: 10
    getAllShowWithSearchAndPaginationUrlForView: "/shows/view/search/{page}?searchPhrase={search}&size={size}"
  seasonService:
    baseUrl: ${SEASON_SERVICE_BASE_URL:http://localhost:8082}
    timeOut: 10
    getAllByShowIdUrl: "/seasons/view/getAll/{showId}"